branch-defaults:
  default:
    environment: WalletController-env-prod
  dev:
    environment: WalletController-env-prod
  master:
    environment: WalletController-env-prod
environment-defaults:
  WalletController-env-prod:
    branch: null
    repository: null
global:
  application_name: wallet-controller
  default_ec2_keyname: null
  default_platform: Go 1 running on 64bit Amazon Linux 2
  default_region: sa-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
